"""Remote help: let a sponsor sign in to this computer, because the person said yes.

The prepared link can carry a sponsor's PUBLIC ssh keys. The person decides on
the web page; only a consented choice reaches the machine. `genesis init` then
parks the keys at `<root>/remote-help.keys` (public material, nothing secret)
and the installer calls `genesis remote-help enable`, which does the one thing
that needs administrator rights on Windows, or a password on macOS: turn on the
login service and install those keys. Everything it writes is marked
`genesis-remote-help` so `genesis remote-help off` can take it all back.

One source for every installer (the window, the by-hand PowerShell, the shell
script): they call this, they do not each carry their own copy of it.
"""

from __future__ import annotations

import json
import os
import platform
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .seed import HELPER_KEY_RE, HELPER_KEYS_MAX

SUFFIX = "genesis-remote-help"
KEYS_FILE = "remote-help.keys"       # under the Genesis root, written by init from a consented seed
MARKER = "remote-help.json"          # under the data dir once enabled


def data_dir() -> Path:
    if os.name == "nt" and os.environ.get("LOCALAPPDATA"):
        d = Path(os.environ["LOCALAPPDATA"]) / "Genesis"
    else:
        d = Path.home() / ".genesis-app"
    d.mkdir(parents=True, exist_ok=True)
    return d


def valid_keys(keys) -> list:
    out = []
    for k in keys or []:
        if not isinstance(k, str):
            continue
        t = k.strip()
        if len(t) > 600 or not HELPER_KEY_RE.match(t) or t in out:
            continue
        out.append(t)
        if len(out) >= HELPER_KEYS_MAX:
            break
    return out


def park_keys(root: Path, helper: dict) -> "Path | None":
    """Called by init from a CONSENTED seed helper. Public keys only."""
    if not isinstance(helper, dict) or helper.get("consented") is not True:
        return None
    keys = valid_keys(helper.get("keys"))
    if not keys:
        return None
    p = Path(root) / KEYS_FILE
    p.write_text("\n".join(keys) + "\n", encoding="utf-8")
    return p


def parked(root: Path) -> list:
    p = Path(root) / KEYS_FILE
    if not p.is_file():
        return []
    return valid_keys(p.read_text(encoding="utf-8").splitlines())


def _tagged(keys: list) -> list:
    return [k + " " + SUFFIX for k in keys]


def windows_enable_script(name: str, keys: list, dir_: Path) -> str:
    """The elevated PowerShell 5.1 script: OpenSSH server on, firewall rule,
    keys merged into the right authorized-keys file with the right ACL, no sleep
    on mains power, Tailscale via winget if absent, a marker, and the removal
    script beside it. Exit 0 on success."""
    key_lines = ",\r\n".join('  "' + k.replace('"', "") + '"' for k in _tagged(keys))
    marker = str(dir_ / MARKER)
    remove_path = str(dir_ / "Remove-RemoteHelp.ps1")
    log = str(dir_ / "install.log")
    when = datetime.now().isoformat(timespec="seconds")
    name_safe = name.replace('"', "")
    remove = windows_remove_script()
    return f"""# Turns on remote help from {name_safe}. Generated by Genesis {when}.
# Public keys only. Undo with Remove-RemoteHelp.ps1 in this folder.
$ErrorActionPreference = "Continue"
$log = "{log}"
function L($t) {{ try {{ Add-Content -Path $log -Value ("{{0}}  remote-help(elevated): {{1}}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $t) }} catch {{ }} }}
$keys = @(
{key_lines}
)
try {{
  $cap = Get-WindowsCapability -Online | Where-Object Name -like "OpenSSH.Server*"
  if ($cap -and $cap.State -ne "Installed") {{ L "installing OpenSSH.Server"; Add-WindowsCapability -Online -Name $cap.Name | Out-Null }}
}} catch {{ L ("capability: " + $_.Exception.Message) }}
try {{ Set-Service -Name sshd -StartupType Automatic; Start-Service sshd; L "sshd automatic + started" }} catch {{ L ("sshd: " + $_.Exception.Message); exit 3 }}
try {{
  if (-not (Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue)) {{
    New-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -DisplayName "OpenSSH Server (sshd)" -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 | Out-Null
    L "firewall rule added"
  }}
}} catch {{ L ("firewall: " + $_.Exception.Message) }}
$user = $env:USERNAME
$isAdmin = $false
try {{ $isAdmin = @(Get-LocalGroupMember -Group "Administrators" -ErrorAction SilentlyContinue | Where-Object {{ $_.Name -like ("*\\" + $user) }}).Count -gt 0 }} catch {{ }}
if ($isAdmin) {{
  $f = Join-Path $env:ProgramData "ssh\\administrators_authorized_keys"
}} else {{
  $sshDir = Join-Path $HOME ".ssh"
  if (-not (Test-Path $sshDir)) {{ New-Item -ItemType Directory -Path $sshDir -Force | Out-Null }}
  $f = Join-Path $sshDir "authorized_keys"
}}
$existing = @()
if (Test-Path $f) {{ $existing = @(Get-Content $f | Where-Object {{ $_.Trim() }}) }}
$merged = @($existing)
foreach ($k in $keys) {{ if (-not ($merged -contains $k)) {{ $merged += $k }} }}
Set-Content -Path $f -Value $merged -Encoding ascii
icacls $f /inheritance:r | Out-Null
icacls $f /grant "SYSTEM:(F)" | Out-Null
if ($isAdmin) {{ icacls $f /grant "BUILTIN\\Administrators:(F)" | Out-Null }} else {{ icacls $f /grant ($user + ":(F)") | Out-Null }}
L ("keys written to " + $f + " (" + $keys.Count + " key(s))")
try {{ powercfg /change standby-timeout-ac 0 | Out-Null }} catch {{ }}
try {{
  if (-not (Get-Command tailscale -ErrorAction SilentlyContinue) -and -not (Test-Path "C:\\Program Files\\Tailscale\\tailscale-ipn.exe")) {{
    if (Get-Command winget -ErrorAction SilentlyContinue) {{ L "installing Tailscale via winget"; winget install -e --id tailscale.tailscale --silent --accept-package-agreements --accept-source-agreements | Out-Null }}
  }}
}} catch {{ L ("tailscale: " + $_.Exception.Message) }}
Set-Content -Path "{marker}" -Value (@{{ name = "{name_safe}"; keyfile = $f; enabledAt = "{when}" }} | ConvertTo-Json) -Encoding UTF8
Set-Content -Path "{remove_path}" -Value @'
{remove}
'@ -Encoding UTF8
L "done"
exit 0
"""


def windows_remove_script() -> str:
    return f"""# Removes remote help that Genesis turned on. Double-click, or run as administrator.
$ErrorActionPreference = "Continue"
$me = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $me.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
  Start-Process powershell -Verb RunAs -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File',('"' + $PSCommandPath + '"'); exit
}}
foreach ($f in @((Join-Path $env:ProgramData "ssh\\administrators_authorized_keys"), (Join-Path $HOME ".ssh\\authorized_keys"))) {{
  if (Test-Path $f) {{
    $keep = @(Get-Content $f | Where-Object {{ $_.Trim() -and ($_ -notmatch ' {SUFFIX}$') }})
    Set-Content -Path $f -Value $keep -Encoding ascii
    if ($keep.Count -eq 0 -and $f -like "*administrators_authorized_keys") {{ try {{ Stop-Service sshd; Set-Service sshd -StartupType Manual }} catch {{ }} }}
  }}
}}
Remove-Item (Join-Path $PSScriptRoot "{MARKER}") -ErrorAction SilentlyContinue
Write-Host "Remote help is off. Nobody can sign in to this computer that way any more."
"""


def posix_enable(name: str, keys: list, dir_: Path, *, run=subprocess.run) -> dict:
    """macOS / Linux: keys into ~/.ssh/authorized_keys (0700 / 0600), the
    marker, the removal script. On macOS also `sudo systemsetup -setremotelogin
    on`, which asks for the person's password in the terminal; on Linux we say
    how to enable sshd rather than guess the distro."""
    ssh = Path.home() / ".ssh"
    ssh.mkdir(mode=0o700, exist_ok=True)
    try:
        os.chmod(ssh, 0o700)
    except OSError:
        pass
    ak = ssh / "authorized_keys"
    existing = ak.read_text(encoding="utf-8").splitlines() if ak.is_file() else []
    merged = [ln for ln in existing if ln.strip()]
    for k in _tagged(keys):
        if k not in merged:
            merged.append(k)
    ak.write_text("\n".join(merged) + "\n", encoding="utf-8")
    try:
        os.chmod(ak, 0o600)
    except OSError:
        pass
    remove = dir_ / "remove-remote-help.sh"
    remove.write_text(
        "#!/bin/sh\n# Removes remote help that Genesis turned on.\n"
        f"AK=\"$HOME/.ssh/authorized_keys\"\n"
        f"[ -f \"$AK\" ] && grep -v ' {SUFFIX}$' \"$AK\" > \"$AK.tmp\" && mv \"$AK.tmp\" \"$AK\" && chmod 600 \"$AK\"\n"
        f"rm -f \"{dir_ / MARKER}\"\n"
        "echo 'Remote help is off.'\n", encoding="utf-8")
    try:
        os.chmod(remove, 0o755)
    except OSError:
        pass
    note = ""
    if platform.system() == "Darwin":
        print(f"Turning on remote help from {name}; your Mac will ask for your password.", file=sys.stderr)
        r = run(["sudo", "systemsetup", "-setremotelogin", "on"])
        note = "remote login on" if getattr(r, "returncode", 1) == 0 else "remote login NOT turned on (System Settings > General > Sharing > Remote Login does the same)"
    elif platform.system() == "Linux":
        note = "keys installed; enable the ssh server for your distro (e.g. `sudo systemctl enable --now ssh`)"
    (dir_ / MARKER).write_text(json.dumps({"name": name, "keyfile": str(ak),
                                           "enabledAt": datetime.now().isoformat(timespec="seconds"),
                                           "note": note}, indent=2), encoding="utf-8")
    return {"keyfile": ak, "remove": remove, "note": note}


def status(dir_: Path) -> "dict | None":
    p = Path(dir_) / MARKER
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {"name": "?", "keyfile": "?", "enabledAt": "?"}


def windows_enable(name: str, keys: list, dir_: Path, *, run=subprocess.run) -> int:
    """Write the elevated script and run it with a UAC prompt; returns its exit code."""
    script = dir_ / "enable-remote-help.ps1"
    script.write_text(windows_enable_script(name, keys, dir_), encoding="utf-8")
    cmd = ["powershell", "-NoProfile", "-Command",
           "$p = Start-Process powershell -Verb RunAs -Wait -PassThru -WindowStyle Hidden "
           "-ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File','\"" + str(script) + "\"'); exit $p.ExitCode"]
    r = run(cmd)
    return getattr(r, "returncode", 1)
