"""Cross-platform heartbeat scheduler with pause / resume / status.

The heartbeat (`genesis heartbeat`) runs the due growth loops. This module owns
how that wake gets *scheduled* on each OS, and how a person pauses, resumes, and
inspects it, the same three verbs everywhere, regardless of the substrate under
them:

    macOS    → launchd LaunchAgent (StartInterval)
    Windows  → Task Scheduler job (schtasks, hourly)
    Linux    → systemd --user timer if available, else crontab

Two design choices keep this honest across substrates:

1. **Pause is a portable sentinel, not an OS toggle.** `genesis pause` writes
   `<root>/heartbeat.paused`; `cmd_heartbeat` checks it first and exits early.
   This is identical on every OS and survives the OS job machinery being weird
   (launchctl bootout semantics, schtasks /Change quirks). The OS job stays
   registered; the sentinel is the source of truth for whether work happens.

2. **The wrapper is generated per-OS** (a `.sh` on POSIX, a `.cmd` on Windows),
   pinning GENESIS_ROOT + PYTHONPATH + the python that ran setup, so the job
   doesn't depend on the user's shell environment at wake time.
"""

from __future__ import annotations

import os
import platform
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

LABEL = "ai.genesis.heartbeat"
WINDOWS_TASK_NAME = "GenesisHeartbeat"
INTERVAL_SECONDS = 3600


# ---------------------------------------------------------------------------
# Pause sentinel, the portable source of truth, checked by the heartbeat
# ---------------------------------------------------------------------------

def pause_sentinel(root: Path) -> Path:
    return Path(root) / "heartbeat.paused"


def is_paused(root: Path) -> bool:
    return pause_sentinel(root).exists()


def pause(root: Path) -> Path:
    p = pause_sentinel(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    if not p.exists():
        from datetime import datetime
        p.write_text(f"paused {datetime.now().astimezone().isoformat()}\n", encoding="utf-8")
    return p


def resume(root: Path) -> bool:
    """Remove the pause sentinel. Returns True if it had been paused."""
    p = pause_sentinel(root)
    if p.exists():
        p.unlink()
        return True
    return False


# ---------------------------------------------------------------------------
# Environment the generated wrapper pins
# ---------------------------------------------------------------------------

def import_pythonpath() -> str:
    """The PYTHONPATH the wrapper needs to find the three genesis packages,
    derived from where they're imported from right now. OS-correct separator."""
    import genesis_core as _gc
    import genesis_backend as _gb
    import genesis_memory as _gm
    parts = [
        str(Path(_gc.__file__).parent.parent),
        str(Path(_gb.__file__).parent.parent),
        str(Path(_gm.__file__).parent.parent),
    ]
    return os.pathsep.join(parts)


# ---------------------------------------------------------------------------
# Wrapper generation (per-OS)
# ---------------------------------------------------------------------------

_POSIX_WRAPPER = """\
#!/bin/sh
# Genesis scheduled job, generated by the scheduler.
export GENESIS_ROOT="{root}"
export PYTHONPATH="{pythonpath}"
exec "{python}" -m genesis_core.cli {verb} "$@"
"""

_WINDOWS_WRAPPER = """\
@echo off
REM Genesis scheduled job, generated by the scheduler.
set "GENESIS_ROOT={root}"
set "PYTHONPATH={pythonpath}"
"{python}" -m genesis_core.cli {verb} %*
"""


def generate_wrapper(root: Path, pythonpath: str, python: str, *, verb: str = "heartbeat",
                     stem: str = "heartbeat") -> Path:
    """Write a wrapper that runs `genesis <verb>` for the current OS. `stem` names
    the file (heartbeat.sh / mailcheck.cmd / ...)."""
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    if platform.system() == "Windows":
        wrapper = root / f"{stem}.cmd"
        wrapper.write_text(
            _WINDOWS_WRAPPER.format(root=root, pythonpath=pythonpath, python=python, verb=verb),
            encoding="utf-8",
        )
    else:
        wrapper = root / f"{stem}.sh"
        wrapper.write_text(
            _POSIX_WRAPPER.format(root=root, pythonpath=pythonpath, python=python, verb=verb),
            encoding="utf-8",
        )
        wrapper.chmod(0o755)
    return wrapper


# ---------------------------------------------------------------------------
# launchd plist (macOS), kept as a standalone helper for back-compat
# ---------------------------------------------------------------------------

_PLIST_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{wrapper}</string>
    </array>
    <key>StartInterval</key>
    <integer>{interval}</integer>
    <key>StandardOutPath</key>
    <string>{log}</string>
    <key>StandardErrorPath</key>
    <string>{log}</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
"""


def generate_plist(root: Path, wrapper_path: Path, *, label: str = LABEL,
                   interval: int = INTERVAL_SECONDS, log_stem: str = "heartbeat") -> Path:
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    plist_path = agents_dir / f"{label}.plist"
    plist_path.write_text(
        _PLIST_TEMPLATE.format(
            label=label,
            wrapper=str(wrapper_path),
            interval=interval,
            log=str(Path(root) / f"{log_stem}.log"),
        ),
        encoding="utf-8",
    )
    return plist_path


# ---------------------------------------------------------------------------
# Sponsor mail-check job, a second schedule (10 min), separate from the hourly
# growth heartbeat. Polls the sponsor inbox so replies surface promptly.
# ---------------------------------------------------------------------------

MAIL_LABEL = "ai.genesis.mailcheck"
MAIL_TASK = "GenesisMailCheck"
MAIL_INTERVAL = 600  # 10 minutes


def install_mail_check(root: Path, python: str | None = None) -> tuple[bool, str]:
    """Schedule `genesis check-mail` every 10 minutes for the current OS."""
    root = Path(root)
    python = python or sys.executable
    wrapper = generate_wrapper(root, import_pythonpath(), python, verb="check-mail", stem="mailcheck")
    sysname = platform.system()
    if sysname == "Darwin":
        plist = generate_plist(root, wrapper, label=MAIL_LABEL, interval=MAIL_INTERVAL, log_stem="mailcheck")
        uid = subprocess.run(["id", "-u"], capture_output=True, text=True).stdout.strip()
        r = subprocess.run(["launchctl", "bootstrap", f"gui/{uid}", str(plist)], capture_output=True, text=True)
        ok = r.returncode == 0 or "already" in r.stderr.lower() or r.returncode == 36
        return ok, f"launchd mail-check every 10 min ({plist})" if ok else f"launchctl: {r.stderr.strip()}"
    if sysname == "Windows":
        r = subprocess.run(
            ["schtasks", "/Create", "/SC", "MINUTE", "/MO", "10", "/TN", MAIL_TASK,
             "/TR", f'"{wrapper}"', "/F"],
            capture_output=True, text=True,
        )
        ok = r.returncode == 0
        return ok, (f"Task Scheduler '{MAIL_TASK}' every 10 min" if ok else f"schtasks: {(r.stderr or r.stdout).strip()}")
    # Linux cron
    mark = "# genesis-mailcheck"
    cur = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    lines = [ln for ln in (cur.stdout.splitlines() if cur.returncode == 0 else []) if mark not in ln]
    lines.append(f'*/10 * * * * "{wrapper}"  {mark}')
    w = subprocess.run(["crontab", "-"], input="\n".join(lines) + "\n", capture_output=True, text=True)
    return w.returncode == 0, "cron mail-check every 10 min" if w.returncode == 0 else "could not write crontab"


def uninstall_mail_check(root: Path) -> tuple[bool, str]:
    sysname = platform.system()
    if sysname == "Darwin":
        plist = Path.home() / "Library" / "LaunchAgents" / f"{MAIL_LABEL}.plist"
        uid = subprocess.run(["id", "-u"], capture_output=True, text=True).stdout.strip()
        subprocess.run(["launchctl", "bootout", f"gui/{uid}/{MAIL_LABEL}"], capture_output=True, text=True)
        if plist.exists():
            plist.unlink()
        return True, "mail-check removed"
    if sysname == "Windows":
        subprocess.run(["schtasks", "/Delete", "/TN", MAIL_TASK, "/F"], capture_output=True, text=True)
        return True, "mail-check removed"
    mark = "# genesis-mailcheck"
    cur = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    kept = [ln for ln in (cur.stdout.splitlines() if cur.returncode == 0 else []) if mark not in ln]
    subprocess.run(["crontab", "-"], input="\n".join(kept) + ("\n" if kept else ""), capture_output=True, text=True)
    return True, "mail-check removed"


# ---------------------------------------------------------------------------
# The Scheduler abstraction
# ---------------------------------------------------------------------------

@dataclass
class ScheduleStatus:
    os_name: str
    registered: bool          # is the OS-level job installed?
    paused: bool              # is the portable sentinel present?
    detail: str               # human-readable backend detail
    wrapper: Path | None = None

    @property
    def state(self) -> str:
        if not self.registered:
            return "not scheduled"
        return "paused" if self.paused else "running"


class Scheduler:
    """Base: owns the sentinel-based pause/resume and the wrapper; subclasses
    implement OS job install/uninstall/registration-check."""

    def __init__(self, root: Path, python: str | None = None):
        self.root = Path(root)
        self.python = python or sys.executable

    # --- portable pause/resume (identical on every OS) ---
    def pause(self) -> Path:
        return pause(self.root)

    def resume(self) -> bool:
        return resume(self.root)

    def is_paused(self) -> bool:
        return is_paused(self.root)

    # --- per-OS hooks (overridden) ---
    def _install_os_job(self, wrapper: Path) -> tuple[bool, str]:
        raise NotImplementedError

    def _uninstall_os_job(self) -> tuple[bool, str]:
        raise NotImplementedError

    def _is_registered(self) -> bool:
        raise NotImplementedError

    def _detail(self) -> str:
        return ""

    # --- public API ---
    def install(self) -> ScheduleStatus:
        wrapper = generate_wrapper(self.root, import_pythonpath(), self.python)
        ok, detail = self._install_os_job(wrapper)
        return ScheduleStatus(
            os_name=platform.system(),
            registered=ok and self._is_registered(),
            paused=self.is_paused(),
            detail=detail,
            wrapper=wrapper,
        )

    def uninstall(self) -> ScheduleStatus:
        ok, detail = self._uninstall_os_job()
        return ScheduleStatus(
            os_name=platform.system(),
            registered=self._is_registered(),
            paused=self.is_paused(),
            detail=detail,
        )

    def status(self) -> ScheduleStatus:
        wrapper = self.root / ("heartbeat.cmd" if platform.system() == "Windows" else "heartbeat.sh")
        return ScheduleStatus(
            os_name=platform.system(),
            registered=self._is_registered(),
            paused=self.is_paused(),
            detail=self._detail(),
            wrapper=wrapper if wrapper.exists() else None,
        )


class LaunchdScheduler(Scheduler):
    def _plist_path(self) -> Path:
        return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"

    def _install_os_job(self, wrapper: Path) -> tuple[bool, str]:
        plist = generate_plist(self.root, wrapper)
        uid = subprocess.run(["id", "-u"], capture_output=True, text=True).stdout.strip()
        r = subprocess.run(
            ["launchctl", "bootstrap", f"gui/{uid}", str(plist)],
            capture_output=True, text=True,
        )
        if r.returncode == 0:
            return True, f"launchd job loaded ({plist})"
        if "already" in r.stderr.lower() or r.returncode == 36:
            return True, "launchd job already loaded"
        return False, f"launchctl: {r.stderr.strip()} (load manually: launchctl bootstrap gui/$(id -u) {plist})"

    def _uninstall_os_job(self) -> tuple[bool, str]:
        plist = self._plist_path()
        uid = subprocess.run(["id", "-u"], capture_output=True, text=True).stdout.strip()
        subprocess.run(["launchctl", "bootout", f"gui/{uid}/{LABEL}"], capture_output=True, text=True)
        if plist.exists():
            plist.unlink()
        return True, "launchd job removed"

    def _is_registered(self) -> bool:
        return self._plist_path().exists()

    def _detail(self) -> str:
        r = subprocess.run(["launchctl", "list", LABEL], capture_output=True, text=True)
        if r.returncode == 0:
            return "launchd: loaded, hourly"
        return "launchd: plist present, not currently loaded" if self._is_registered() else "launchd: not registered"


class WindowsScheduler(Scheduler):
    def _install_os_job(self, wrapper: Path) -> tuple[bool, str]:
        # /SC HOURLY runs the wrapper once an hour. /F overwrites an existing job.
        r = subprocess.run(
            ["schtasks", "/Create", "/SC", "HOURLY", "/TN", WINDOWS_TASK_NAME,
             "/TR", f'"{wrapper}"', "/F"],
            capture_output=True, text=True,
        )
        if r.returncode == 0:
            return True, f"Task Scheduler job '{WINDOWS_TASK_NAME}' created (hourly)"
        return False, f"schtasks: {(r.stderr or r.stdout).strip()}"

    def _uninstall_os_job(self) -> tuple[bool, str]:
        r = subprocess.run(
            ["schtasks", "/Delete", "/TN", WINDOWS_TASK_NAME, "/F"],
            capture_output=True, text=True,
        )
        if r.returncode == 0:
            return True, f"Task Scheduler job '{WINDOWS_TASK_NAME}' removed"
        return True, f"schtasks delete: {(r.stderr or r.stdout).strip()}"

    def _is_registered(self) -> bool:
        r = subprocess.run(
            ["schtasks", "/Query", "/TN", WINDOWS_TASK_NAME],
            capture_output=True, text=True,
        )
        return r.returncode == 0

    def _detail(self) -> str:
        return f"Task Scheduler: '{WINDOWS_TASK_NAME}' " + ("registered, hourly" if self._is_registered() else "not registered")


class CronScheduler(Scheduler):
    """Linux fallback: a crontab line invoking the wrapper hourly. systemd --user
    timers are nicer but cron is universally present; keep it simple and portable."""

    _MARK = "# genesis-heartbeat"

    def _read_crontab(self) -> str:
        r = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        return r.stdout if r.returncode == 0 else ""

    def _write_crontab(self, text: str) -> bool:
        r = subprocess.run(["crontab", "-"], input=text, capture_output=True, text=True)
        return r.returncode == 0

    def _install_os_job(self, wrapper: Path) -> tuple[bool, str]:
        existing = [ln for ln in self._read_crontab().splitlines() if self._MARK not in ln]
        existing.append(f'0 * * * * "{wrapper}"  {self._MARK}')
        if self._write_crontab("\n".join(existing) + "\n"):
            return True, "crontab line installed (hourly)"
        return False, "could not write crontab (is cron available?)"

    def _uninstall_os_job(self) -> tuple[bool, str]:
        kept = [ln for ln in self._read_crontab().splitlines() if self._MARK not in ln]
        self._write_crontab("\n".join(kept) + ("\n" if kept else ""))
        return True, "crontab line removed"

    def _is_registered(self) -> bool:
        return self._MARK in self._read_crontab()

    def _detail(self) -> str:
        return "cron: hourly line present" if self._is_registered() else "cron: not registered"


def get_scheduler(root: Path, python: str | None = None) -> Scheduler:
    sysname = platform.system()
    if sysname == "Darwin":
        return LaunchdScheduler(root, python)
    if sysname == "Windows":
        return WindowsScheduler(root, python)
    return CronScheduler(root, python)
